import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
import ConvexClientProvider from "./ConvexClientProvider";
import { Header } from "./_components/Header";

const outfit = Outfit({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body className={outfit.className}>
        <ConvexClientProvider>
          {" "}
          <Provider>
            {" "}
            
            {children}
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
